<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYFUoYTb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYFUoYTb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYFUoYTb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYFUoYTb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYFUoYTb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YFUoYTb',
    'container.build_id' => '4cbf4a5e',
    'container.build_time' => 1652868792,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYFUoYTb');
