<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\UserController::create'], [], [['text', '/register']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/login']], [], []],
    'user_edit' => [[], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/user/edit']], [], []],
    'video' => [[], ['_controller' => 'App\\Controller\\VideoController::index'], [], [['text', '/video']], [], []],
    'video_new' => [[], ['_controller' => 'App\\Controller\\VideoController::create'], [], [['text', '/video/new']], [], []],
    'video_list' => [[], ['_controller' => 'App\\Controller\\VideoController::videos'], [], [['text', '/video/list']], [], []],
    'video_detail' => [['id'], ['_controller' => 'App\\Controller\\VideoController::video'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/video/detail']], [], []],
    'video_remove' => [['id'], ['_controller' => 'App\\Controller\\VideoController::remove'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/video/remove']], [], []],
];
